name: Testing API
on: [push, pull_request]
jobs:
  testing_api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{secrets.SERVICE_ACCOUNT_KEY}}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Creating and activate virtual enve
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          pip install dvc[gs]
          pip install -r requeriments_test.txt
      - name: Test API
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-track
          pytest test.py